vim.opt.backup = false -- creates a backup file
vim.opt.clipboard = "unnamedplus" -- allows neovim to access the system clipboard
vim.opt.fileencoding = "utf-8" -- the encoding written to a file
vim.opt.hlsearch = true -- highlight all matches on previous search pattern
vim.opt.ignorecase = true -- ignore case in search patterns
vim.opt.termguicolors = true -- set term gui colors (most terminals support this)
vim.opt.relativenumber = true -- set relative numbered lines
vim.opt.number = true -- set numbered lines
vim.opt.splitbelow = true -- force all horizontal splits to go below current window
vim.opt.splitright = true -- force all vertical splits to go to the right of current window
vim.opt.mouse = "a" -- allow the mouse to be used in neovim
vim.opt.shiftwidth = 2 -- the number of spaces inserted for each indentation
vim.opt.tabstop = 2 -- insert 2 spaces for a tab
vim.g.mapleader = " " --Remap space as leader key
vim.g.maplocalleader = " " --Remap space as leader key
